onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Segway_auth_flow_tb/SS_n
add wave -noupdate /Segway_auth_flow_tb/SCLK
add wave -noupdate /Segway_auth_flow_tb/MOSI
add wave -noupdate /Segway_auth_flow_tb/MISO
add wave -noupdate /Segway_auth_flow_tb/INT
add wave -noupdate /Segway_auth_flow_tb/A2D_SS_n
add wave -noupdate /Segway_auth_flow_tb/A2D_SCLK
add wave -noupdate /Segway_auth_flow_tb/A2D_MOSI
add wave -noupdate /Segway_auth_flow_tb/A2D_MISO
add wave -noupdate /Segway_auth_flow_tb/RX_TX
add wave -noupdate /Segway_auth_flow_tb/PWM1_rght
add wave -noupdate /Segway_auth_flow_tb/PWM2_rght
add wave -noupdate /Segway_auth_flow_tb/PWM1_lft
add wave -noupdate /Segway_auth_flow_tb/PWM2_lft
add wave -noupdate /Segway_auth_flow_tb/piezo
add wave -noupdate /Segway_auth_flow_tb/piezo_n
add wave -noupdate /Segway_auth_flow_tb/cmd_sent
add wave -noupdate /Segway_auth_flow_tb/rst_n
add wave -noupdate /Segway_auth_flow_tb/clk
add wave -noupdate /Segway_auth_flow_tb/RST_n
add wave -noupdate /Segway_auth_flow_tb/cmd
add wave -noupdate /Segway_auth_flow_tb/send_cmd
add wave -noupdate /Segway_auth_flow_tb/rider_lean
add wave -noupdate /Segway_auth_flow_tb/ld_cell_lft
add wave -noupdate /Segway_auth_flow_tb/ld_cell_rght
add wave -noupdate /Segway_auth_flow_tb/steerPot
add wave -noupdate /Segway_auth_flow_tb/batt
add wave -noupdate /Segway_auth_flow_tb/OVR_I_lft
add wave -noupdate /Segway_auth_flow_tb/OVR_I_rght
add wave -noupdate /Segway_auth_flow_tb/iDUT/lft_spd
add wave -noupdate /Segway_auth_flow_tb/iDUT/rght_spd
add wave -noupdate -divider Physics
add wave -noupdate /Segway_auth_flow_tb/iPHYS/lft_duty
add wave -noupdate /Segway_auth_flow_tb/iPHYS/rght_duty
add wave -noupdate /Segway_auth_flow_tb/iPHYS/rst_n
add wave -noupdate /Segway_auth_flow_tb/iPHYS/rst_synch
add wave -noupdate /Segway_auth_flow_tb/iPHYS/time_since_rise_lft
add wave -noupdate /Segway_auth_flow_tb/iPHYS/time_since_rise_rght
add wave -noupdate /Segway_auth_flow_tb/iPHYS/time_since_calc
add wave -noupdate /Segway_auth_flow_tb/iPHYS/az
add wave -noupdate /Segway_auth_flow_tb/iPHYS/torque_lft
add wave -noupdate /Segway_auth_flow_tb/iPHYS/torque_rght
add wave -noupdate /Segway_auth_flow_tb/iPHYS/any_are_one_ff1
add wave -noupdate /Segway_auth_flow_tb/iPHYS/calc_physics
add wave -noupdate /Segway_auth_flow_tb/iPHYS/net_torque
add wave -noupdate /Segway_auth_flow_tb/iPHYS/omega_lft
add wave -noupdate /Segway_auth_flow_tb/iPHYS/omega_rght
add wave -noupdate /Segway_auth_flow_tb/iPHYS/theta_lft
add wave -noupdate /Segway_auth_flow_tb/iPHYS/theta_rght
add wave -noupdate /Segway_auth_flow_tb/iPHYS/rotation_platform
add wave -noupdate -format Analog-Step -height 74 -max 65.000000000000014 -min -2.0 -radix decimal /Segway_auth_flow_tb/iPHYS/omega_platform
add wave -noupdate -format Analog-Step -height 74 -max 1.0 -min -4.0 -radix decimal /Segway_auth_flow_tb/iPHYS/theta_platform
add wave -noupdate -divider {Inertial Integrator}
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/clk
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/rst_n
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/vld
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_rt
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/AZ
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_int
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_rt_comp
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_rt_comp_ext
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/AZ_comp
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_acc_product
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_acc
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/fusion_ptch_offset
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_acc_piped
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/ptch_rt_comp_ext_piped
add wave -noupdate /Segway_auth_flow_tb/iDUT/iNEMO/iINT/fusion_ptch_offset_piped
add wave -noupdate -divider {Motor Drive}
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/clk
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/rst_n
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/lft_spd
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/rght_spd
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_lft
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_rght
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM1_lft
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM2_lft
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM1_rght
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM2_rght
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_shtdwn
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/lft_spd_synch
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/rght_spd_synch
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_ff1
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_ff2
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_ff3
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_cnt
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_cycle_cnt
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_inc_blank_n
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/lft_mag
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/rght_mag
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_lft
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_rght
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_lft_n
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_rght_n
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/PWM_synch
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/OVR_I_rise
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/ovr_I_blank
add wave -noupdate /Segway_auth_flow_tb/iDUT/iDRV/LED
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {24138 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 384
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1631756 ns}
